import 'package:flutter/material.dart';
import '../models/user_model.dart';
import '../services/user_service.dart';
import 'comments_page.dart';
import '../services/favorite_service.dart';
import '../generated/app_localizations.dart';

class SearchPage extends StatefulWidget {
  const SearchPage({super.key});

  @override
  State<SearchPage> createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
final TextEditingController searchController = TextEditingController();
final UserService userService = UserService();
final Set<String> favoriteUsers = {};
final FavoriteService favoriteService = FavoriteService();

List<UserModel> allCraftsmen = [];
List<UserModel> filteredCraftsmen = [];

bool loading = true;
String selectedProfession = "";
String sortType = "rating";
final List<String> cities = [
"Adana",
"Adıyaman",
"Afyonkarahisar",
"Ağrı",
"Aksaray",
"Amasya",
"Ankara",
"Antalya",
"Ardahan",
"Artvin",
"Aydın",
"Balıkesir",
"Bartın",
"Batman",
"Bayburt",
"Bilecik",
"Bingöl",
"Bitlis",
"Bolu",
"Burdur",
"Bursa",
"Çanakkale",
"Çankırı",
"Çorum",
"Denizli",
"Diyarbakır",
"Düzce",
"Edirne",
"Elazığ",
"Erzincan",
"Erzurum",
"Eskişehir",
"Gaziantep",
"Giresun",
"Gümüşhane",
"Hakkari",
"Hatay",
"Iğdır",
"Isparta",
"İstanbul",
"İzmir",
"Kahramanmaraş",
"Karabük",
"Karaman",
"Kars",
"Kastamonu",
"Kayseri",
"Kırıkkale",
"Kırklareli",
"Kırşehir",
"Kilis",
"Kocaeli",
"Konya",
"Kütahya",
"Malatya",
"Manisa",
"Mardin",
"Mersin",
"Muğla",
"Muş",
"Nevşehir",
"Niğde",
"Ordu",
"Osmaniye",
"Rize",
"Sakarya",
"Samsun",
"Siirt",
"Sinop",
"Sivas",
"Şanlıurfa",
"Şırnak",
"Tekirdağ",
"Tokat",
"Trabzon",
"Tunceli",
"Uşak",
"Van",
"Yalova",
"Yozgat",
"Zonguldak",
];

final List<String> jobs = [
"Elektrikçi",
"Su Tesisatçısı",
"Boyacı",
"Fayans Ustası",
"Alçı Ustası",
"Sıvacı",
"Kaynakçı",
"PVC Doğrama",
"Klimacı",
"Kombi Servisi",
"Çatı Ustası",
"Demirci",
"Marangoz",
"Mobilyacı",
"Parkeci",
"Camcı",
"Anahtarcı",
"Bahçıvan",
"Temizlik",
"Nakliyeci",
"Asansör Servisi",
"Çelik Kapı",
"Doğalgaz",
"Alüminyum Doğrama",
"Güneş Enerjisi",
"Mantolama",
"İzolasyon",
"Kalıpçı",
"Betoncu",
"Vinç Hizmeti",
  "Duvar Ustası",
  "Duvar Kağıdı Ustası",
  "Kalıp Ustası",
  "Demir Bağlama",
  "Seramik Ustası",
  "Granit Ustası",
  "Mermer Ustası",
  "Mutfak Dolabı",
  "Vestiyer",
  "Banyo Dolabı",
  "Çelik Çatı",
  "Ahşap Çatı",
  "Su Yalıtımı",
  "Ses Yalıtımı",
  "Çatı İzolasyonu",
  "Dış Cephe Boya",
  "İç Cephe Boya",
  "Saten Alçı",
  "Kartonpiyer",
  "Asma Tavan",
  "LED Aydınlatma",
  "Kamera Sistemleri",
  "Alarm Sistemleri",
  "Yangın Sistemleri",
  "Uydu Sistemleri",
  "İnternet Tesisatı",
  "Elektrik Arıza",
  "Su Kaçağı",
  "Kombi Bakımı",
  "Klima Montajı",
  "Klima Bakımı",
  "PVC Pencere",
  "Alüminyum Doğrama",
  "Panjur",
  "Sineklik",
  "Peyzaj",
  "Bahçe Sulama",
  "Havuz Yapımı",
  "Havuz Bakımı",
  "Çim Döşeme",
  "Oto Elektrik",
  "Oto Kaporta",
  "Oto Boya",
  "Oto Mekanik",
  "Oto Ekspertiz",
  "Ev Temizliği",
  "Ofis Temizliği",
  "İnşaat Temizliği",
  "Cam Temizliği",
  "Nakliye",
  "Parça Eşya Taşıma",
  "Vinç Kiralama",
  "Forklift",
  "İş Makinesi",
  "Dozer",
  "Kepçe",
  "Ekskavatör",
  "Asfalt",
  "Parke Taşı",
  "Kilit Taşı",
  "Bahçe Duvarı",
  "Ferforje",
  "Çit Sistemleri",
  "Otomatik Kapı",
  "Pergola",
  "Kış Bahçesi",
  "Cam Balkon",
  "Isı Pompası",
  "Güneş Enerji Sistemi",
  "Solar Panel",
  "Kaloriferci",
  "Kalorifer Tesisatı",
  "Petek Temizleme",
  "Petek Montajı",
  "Petek Tamiri",
  "Doğalgaz Tesisatı",
  "Kazan Dairesi",
  "Baca Temizliği",
  "Baca Yapımı",
  "Boru Kaynağı",
  "Boru Döşeme",
  "Sondaj",
  "Artezyen",
  "Kuyu Açma",
  "Su Deposu",
  "Su Arıtma",
  "Elektrik Panosu",
  "Jeneratör",
  "Şofben Servisi",
  "Şarj İstasyonu",
  "Fiber İnternet",
  "Network Kurulumu",
  "Bilgisayar Tamiri",
  "Laptop Tamiri",
  "Telefon Tamiri",
  "Televizyon Tamiri",
  "Beyaz Eşya Servisi",
  "Buzdolabı Servisi",
  "Çamaşır Makinesi Servisi",
  "Bulaşık Makinesi Servisi",
  "Fırın Servisi",
  "Aspiratör Servisi",
  "Davlumbaz",
  "Stor Perde",
  "Perde Montajı",
  "Duşakabin",
  "Musluk Tamiri",
  "Klozet Montajı",
  "Lavabo Montajı",
  "Batarya Değişimi",
  "Merdiven",
  "Korkuluk",
  "Çelik Konstrüksiyon",
  "Çelik Merdiven",
  "Çatı Aktarma",
  "Oluk Tamiri",
  "Oluk Montajı",
  "Su İzolasyonu",
  "Epoksi Zemin",
  "Şap",
  "Mozaik",
  "Granit Döşeme",
  "Mermer Cilalama",
  "Mermer Kesimi",
  "Bahçe Düzenleme",
  "Ağaç Budama",
  "Çim Biçme",
  "Rulo Çim",
  "Sulama Sistemi",
  "Bahçe Aydınlatma",
  "Güvenlik Kamerası",
  "CCTV",
  "Alarm Kurulumu",
  "Akıllı Ev",
  "Otomasyon",
  "Kapı Motoru",
  "Garaj Kapısı",
  "Otomatik Kepenk",
  "PVC Kapı",
  "Alüminyum Cephe",
  "Kompozit Cephe",
  "Dış Cephe Mantolama",
  "İç Dekorasyon",
  "Tadilat",
  "Anahtar Teslim",
  "Villa Yapımı",
  "Daire Tadilatı",
  "İşyeri Tadilatı",
  "Çocuk Odası Tasarımı",
  "Mutfak Yenileme",
  "Banyo Yenileme",
  "İnşaat Ustası",
  "Anahtar Teslim İnşaat",
  "Villa Yapımı",
  "Villa Tadilatı",
  "Konut Yapımı",
  "Apartman Yapımı",
  "Kaba İnşaat",
  "İnce İnşaat",
  "Betonarme",
  "Beton Dökümü",
  "Hazır Beton",
  "Şap Ustası",
  "Helikopterli Şap",
  "Beton Kesme",
  "Karot",
  "Karot Delme",
  "Karot Kesim",
  "Kalıpçı",
  "Kalıp Ustası",
  "Kalıp İskelesi",
  "Ahşap Kalıp",
  "Tünel Kalıp",
  "Perde Beton",
  "Demirci",
  "Demir Bağlama",
  "İnşaat Demiri",
  "Demir Donatı",
  "Kaynakçı",
  "Gazaltı Kaynak",
  "Argon Kaynak",
  "Elektrik Kaynağı",
  "Oksijen Kaynak",
  "Çelik Kaynak",
  "Paslanmaz Kaynak",
  "Alüminyum Kaynak",
  "Çelik Konstrüksiyon",
  "Çelik Çatı",
  "Çelik Kolon",
  "Çelik Kiriş",
  "Prefabrik Yapı",
  "Prefabrik Ev",
  "Konteyner Ev",
  "Tiny House",
  "Ahşap Ev",
  "Bungalov",
  "Taş Ev",
  "Yığma Ev",
  "Taş Duvar",
  "Bahçe Duvarı",
  "İstinat Duvarı",
  "Duvar Ustası",
  "Tuğla Duvar",
  "Bims Duvar",
  "Gazbeton",
  "Briket Duvar",
  "Taş Kaplama",
  "Doğal Taş",
  "Granit Kaplama",
  "Mermer Kaplama",
  "Traverten",
  "Seramik Ustası",
  "Fayans Ustası",
  "Porselen Seramik",
  "Granit Seramik",
  "Mozaik Döşeme",
  "Kilit Taşı",
  "Parke Taşı",
  "Bordür Taşı",
  "Karo Taşı",
  "Çevre Düzenleme",
  "Hafriyat",
  "Kazı Dolgu",
  "Tesviye",
  "Moloz Taşıma",
  "Moloz Atımı",
  "Yıkım",
  "Bina Yıkımı",
  "İş Makinesi",
  "Kepçe",
  "Mini Kepçe",
  "Ekskavatör",
  "Loder",
  "Dozer",
  "Silindir",
  "Greyder",
  "Forklift",
  "Vinç",
  "Sepetli Vinç",
  "Mobil Vinç",
  "Kule Vinç",
  "Platform Kiralama",
  "İskele Kurulumu",
  "Mobil İskele",
  "Dış Cephe İskelesi",
  "Çatı Ustası",
  "Çatı Aktarma",
  "Çatı Tamiri",
  "Kiremit Çatı",
  "Metal Çatı",
  "Sandviç Panel",
  "OSB Çatı",
  "Membran Çatı",
  "Oluk Montajı",
  "Oluk Tamiri",
  "Yağmur Oluğu",
  "Baca Yapımı",
  "Baca Tamiri",
  "Baca Temizliği",
  "Su Yalıtımı",
  "Temel İzolasyonu",
  "Bohçalama",
  "Membran İzolasyon",
  "Bitümlü Membran",
  "Kristalize İzolasyon",
  "Çatı İzolasyonu",
  "Teras İzolasyonu",
  "Isı Yalıtımı",
  "Mantolama",
  "Dış Cephe Mantolama",
  "Fileli Sıva",
  "Söve",
  "Dış Cephe Kaplama",
  "Kompozit Cephe",
  "Fibercement",
  "Alçı Ustası",
  "Saten Alçı",
  "Kaba Sıva",
  "İnce Sıva",
  "Makine Sıvası",
  "Sıvacı",
  "Kartonpiyer",
  "Asma Tavan",
  "Alçıpan",
  "Bölme Duvar",
  "LED Tavan",
  "Gergi Tavan",
  "PVC Tavan",
  "Boyacı",
  "İç Cephe Boya",
  "Dış Cephe Boya",
  "Epoksi Boya",
  "Epoksi Zemin",
  "Zemin Kaplama",
  "Self Leveling",
  "Endüstriyel Zemin",
  "Parlatma Betonu",
  "Cila",
  "Vernik",
  "Elektrikçi",
  "Elektrik Arıza",
  "Elektrik Bakım",
  "Elektrik Tesisatı",
  "Elektrik Panosu",
  "Pano Toplama",
  "Şantiye Elektriği",
  "Endüstriyel Elektrik",
  "Yüksek Gerilim",
  "Alçak Gerilim",
  "Topraklama",
  "Paratoner",
  "Aydınlatma",
  "LED Aydınlatma",
  "LED Döşeme",
  "LED Şerit",
  "Spot Aydınlatma",
  "Bahçe Aydınlatma",
  "Sokak Aydınlatma",
  "Projektör Montajı",
  "Avize Montajı",
  "Korniş Montajı",
  "TV Montajı",
  "Duvar TV Askı",
  "Uydu Anteni",
  "Merkezi Uydu",
  "Çanak Anten",
  "TV Anten",
  "İnternet Tesisatı",
  "Fiber İnternet",
  "Modem Kurulumu",
  "Router Kurulumu",
  "Switch Kurulumu",
  "Network Kurulumu",
  "Network Kablolama",
  "Kablo Çekimi",
  "Cat6 Kablolama",
  "Data Kablolama",
  "Telefon Hattı",
  "Santral Kurulumu",
  "IP Santral",
  "Interkom",
  "Görüntülü Diyafon",
  "Diyafon",
  "Akıllı Ev",
  "Ev Otomasyonu",
  "Bina Otomasyonu",
  "PLC Otomasyon",
  "Endüstriyel Otomasyon",
  "SCADA",
  "Arduino",
  "Raspberry Pi",
  "Elektronikçi",
  "Elektronik Tamiri",
  "Devre Tamiri",
  "Kart Tamiri",
  "Anakart Tamiri",
  "Güç Kaynağı Tamiri",
  "UPS Servisi",
  "Jeneratör",
  "Jeneratör Servisi",
  "Akü Sistemi",
  "Solar İnverter",
  "Güneş Enerji Sistemi",
  "Solar Panel",
  "Panel Montajı",
  "Panel Temizliği",
  "Şarj İstasyonu",
  "Elektrikli Araç Şarj",
  "Kamera Sistemleri",
  "CCTV",
  "IP Kamera",
  "Güvenlik Kamerası",
  "Kamera Montajı",
  "Kamera Bakımı",
  "Kamera Arıza",
  "Kayıt Cihazı",
  "NVR",
  "DVR",
  "Alarm Sistemleri",
  "Hırsız Alarmı",
  "Yangın Alarmı",
  "Yangın Sistemleri",
  "Duman Dedektörü",
  "Gaz Dedektörü",
  "Kapı Sensörü",
  "Hareket Sensörü",
  "Kartlı Geçiş",
  "Parmak İzi Sistemi",
  "Yüz Tanıma Sistemi",
  "Turnike Sistemi",
  "Bariyer Sistemi",
  "Otomatik Kapı",
  "Garaj Kapısı",
  "Kepenk Motoru",
  "Otomatik Kepenk",
  "Fotoselli Kapı",
  "Bahçe Kapısı Motoru",
  "Akıllı Kilit",
  "Kapı Otomatiği",
  "Asansör",
  "Asansör Bakımı",
  "Asansör Revizyon",
  "Yük Asansörü",
  "Yürüyen Merdiven",
  "Klima Elektriği",
  "Kombi Elektriği",
  "Havalandırma Otomasyonu",
  "Soğuk Hava Deposu",
  "Endüstriyel Soğutma",
  "Sunucu Odası",
  "Server Kurulumu",
  "Rack Kabin",
  "Data Center",
  "POS Kurulumu",
  "Barkod Sistemi",
  "Yazarkasa Servisi",
  "Bilgisayar Tamiri",
  "Bilgisayar Bakımı",
  "Laptop Tamiri",
  "Notebook Tamiri",
  "Macbook Tamiri",
  "Tablet Tamiri",
  "Cep Telefonu Tamiri",
  "iPhone Tamiri",
  "Android Tamiri",
  "Ekran Değişimi",
  "Batarya Değişimi",
  "Hoparlör Tamiri",
  "Mikrofon Tamiri",
  "Şarj Soketi",
  "Yazıcı Tamiri",
  "Fotokopi Makinesi",
  "Tarayıcı Tamiri",
  "Monitör Tamiri",
  "Televizyon Tamiri",
  "LED TV Tamiri",
  "OLED TV Tamiri",
  "QLED TV Tamiri",
  "Projeksiyon Tamiri",
  "Su Tesisatçısı",
  "Su Tesisatı",
  "Temiz Su Tesisatı",
  "Pis Su Tesisatı",
  "Atık Su Tesisatı",
  "Yağmur Suyu Tesisatı",
  "Yangın Tesisatı",
  "Yangın Sprinkler",
  "Sprinkler Sistemi",
  "Hidrofor",
  "Su Deposu",
  "Su Deposu Temizliği",
  "Su Deposu Montajı",
  "Su Deposu Tamiri",
  "Su Kaçağı",
  "Su Kaçağı Tespiti",
  "Termal Kamera Tespiti",
  "Kırmadan Su Kaçağı",
  "Gider Açma",
  "Tıkalı Gider",
  "Kanal Açma",
  "Kanal Temizleme",
  "Logar Temizliği",
  "Rögar Temizliği",
  "Klozet Montajı",
  "Klozet Tamiri",
  "Gömme Rezervuar",
  "Rezervuar Tamiri",
  "Lavabo Montajı",
  "Lavabo Tamiri",
  "Evye Montajı",
  "Batarya Montajı",
  "Musluk Tamiri",
  "Musluk Değişimi",
  "Duş Seti",
  "Duşakabin",
  "Duşakabin Montajı",
  "Duşakabin Tamiri",
  "Jakuzi Montajı",
  "Küvet Montajı",
  "Pisuar Montajı",
  "Armatür Montajı",
  "Su Sayacı",
  "Vana Değişimi",
  "Pislik Tutucu",
  "Pompa Montajı",
  "Sirkülasyon Pompası",
  "Basınç Tankı",
  "Doğalgaz",
  "Doğalgaz Tesisatı",
  "Doğalgaz Projesi",
  "Doğalgaz Kaçağı",
  "Doğalgaz Hattı",
  "Doğalgaz Dönüşümü",
  "Kombi Servisi",
  "Kombi Tamiri",
  "Kombi Bakımı",
  "Kombi Montajı",
  "Kombi Sökme",
  "Kombi Taşıma",
  "Kombi Arızası",
  "Kombi Kart Tamiri",
  "Kombi Anakart",
  "Kombi Fanı",
  "Kombi Eşanjörü",
  "Kombi Gaz Ayarı",
  "Kombi Petek Temizliği",
  "Kalorifer Tesisatı",
  "Kaloriferci",
  "Kalorifer Tamiri",
  "Kalorifer Kazanı",
  "Merkezi Isıtma",
  "Yerden Isıtma",
  "Yerden Isıtma Tesisatı",
  "Petek Montajı",
  "Petek Temizliği",
  "Petek Yıkama",
  "Petek Vanası",
  "Petek Değişimi",
  "Termostatik Vana",
  "Havlupan",
  "Boyler",
  "Boiler",
  "Güneş Enerjisi",
  "Güneş Enerjisi Bakımı",
  "Güneş Enerji Sistemi",
  "Solar Sistem",
  "Solar Panel",
  "Solar Bakım",
  "Isı Pompası",
  "Şofben",
  "Şofben Servisi",
  "Termosifon",
  "Termosifon Servisi",
  "Klima Servisi",
  "Klima Tamiri",
  "Klima Bakımı",
  "Klima Montajı",
  "Klima Demontajı",
  "Klima Gaz Dolumu",
  "Klima Gaz Kaçağı",
  "VRF Sistemleri",
  "Multi Klima",
  "Kaset Klima",
  "Salon Tipi Klima",
  "Havalandırma",
  "Havalandırma Sistemleri",
  "Havalandırma Kanalı",
  "Hava Perdesi",
  "Aspiratör",
  "Davlumbaz",
  "Endüstriyel Davlumbaz",
  "Soğuk Hava Deposu",
  "Chiller",
  "Fan Coil",
  "Soğutma Sistemleri",
  "Buz Makinesi",
  "Su Sebili",
  "Beyaz Eşya Servisi",
  "Buzdolabı Servisi",
  "Derin Dondurucu",
  "Çamaşır Makinesi",
  "Kurutma Makinesi",
  "Bulaşık Makinesi",
  "Fırın Servisi",
  "Ocak Servisi",
  "Ankastre Servisi",
  "Mikrodalga Servisi",
  "Kahve Makinesi",
  "Elektrikli Süpürge",
  "Robot Süpürge",
  "Su Arıtma",
  "Su Arıtma Servisi",
  "Su Arıtma Montajı",
  "Su Arıtma Filtresi",
  "Marangoz",
  "Mobilyacı",
  "Mobilya Ustası",
  "Mobilya Montajı",
  "Mobilya Tamiri",
  "Mobilya Boyama",
  "Mobilya Cilalama",
  "Mobilya Kaplama",
  "Mutfak Dolabı",
  "Mutfak Dolabı Montajı",
  "Mutfak Dolabı Tamiri",
  "Mutfak Tasarımı",
  "Mutfak Yenileme",
  "Banyo Dolabı",
  "Banyo Dolabı Montajı",
  "Vestiyer",
  "Portmanto",
  "Gardırop",
  "Ray Dolap",
  "Gömme Dolap",
  "TV Ünitesi",
  "Kitaplık",
  "Çalışma Masası",
  "Bilgisayar Masası",
  "Yatak Odası",
  "Genç Odası",
  "Çocuk Odası",
  "Bebek Odası",
  "Yemek Odası",
  "Oturma Grubu",
  "Koltuk Tamiri",
  "Koltuk Döşeme",
  "Kanepe Tamiri",
  "Sandalye Tamiri",
  "Ahşap Kapı",
  "Amerikan Kapı",
  "Oda Kapısı",
  "Çelik Kapı",
  "Kapı Montajı",
  "Kapı Tamiri",
  "Kapı Kilidi",
  "Kapı Kolu",
  "Pencere",
  "PVC Pencere",
  "PVC Kapı",
  "PVC Doğrama",
  "PVC Tamiri",
  "PVC Kaynak",
  "Sineklik",
  "Sürgülü Sineklik",
  "Menteşeli Sineklik",
  "Panjur",
  "Otomatik Panjur",
  "Kepenk",
  "Alüminyum Doğrama",
  "Alüminyum Kapı",
  "Alüminyum Pencere",
  "Alüminyum Cephe",
  "Kompozit Cephe",
  "Cam Balkon",
  "Katlanır Cam Balkon",
  "Sürgülü Cam Balkon",
  "Isıcam",
  "Camcı",
  "Cam Değişimi",
  "Cam Tamiri",
  "Vitrin Camı",
  "Ayna",
  "Ayna Montajı",
  "Duşakabin Camı",
  "Temperli Cam",
  "Lamine Cam",
  "Cam Kapı",
  "Ofis Bölme",
  "Cam Bölme",
  "Ferforje",
  "Demir Kapı",
  "Bahçe Kapısı",
  "Balkon Korkuluğu",
  "Merdiven Korkuluğu",
  "Küpeşte",
  "Korkuluk",
  "Çelik Merdiven",
  "Ahşap Merdiven",
  "Pergola",
  "Kamelya",
  "Veranda",
  "Kış Bahçesi",
  "Tente",
  "Mafsallı Tente",
  "Kasetli Tente",
  "Otomatik Tente",
  "Branda",
  "Gölgelik",
  "Ahşap Deck",
  "Lambiri",
  "Masif Ahşap",
  "Lake Boya",
  "Lake Kapak",
  "MDF Kesim",
  "MDF CNC",
  "CNC Kesim",
  "Lazer Kesim",
  "Ahşap Oyma",
  "Ahşap Tornacı",
  "Ahşap Restorasyon",
  "Mobilya Restorasyonu",
  "İç Dekorasyon",
  "Ev Dekorasyonu",
  "Ofis Dekorasyonu",
  "Mağaza Dekorasyonu",
  "Kafe Dekorasyonu",
  "Restoran Dekorasyonu",
  "Showroom Dekorasyonu",
  "3D İç Mekan Tasarımı",
  "Mimari Tasarım",
  "İç Mimar",
  "Dış Cephe Tasarımı",
  "Render Hizmeti",
  "3D Modelleme",
  "AutoCAD Çizimi",
  "Statik Proje",
  "Mekanik Proje",
  "Elektrik Projesi",
  "Ruhsat Projesi",
  "Keşif Hizmeti",
  "Ekspertiz Hizmeti",
  "Danışmanlık",
  "Bahçıvan",
  "Peyzaj",
  "Peyzaj Mimarı",
  "Peyzaj Tasarımı",
  "Bahçe Düzenleme",
  "Bahçe Bakımı",
  "Bahçe Temizliği",
  "Bahçe Sulama",
  "Otomatik Sulama",
  "Damlama Sulama",
  "Çim Ekimi",
  "Rulo Çim",
  "Çim Biçme",
  "Çim Havalandırma",
  "Ağaç Dikimi",
  "Ağaç Budama",
  "Meyve Ağacı Budama",
  "Palmiye Budama",
  "Ağaç Kesimi",
  "Tehlikeli Ağaç Kesimi",
  "Kök Sökme",
  "Çit Yapımı",
  "Tel Çit",
  "Panel Çit",
  "Ferforje Çit",
  "Bahçe Duvarı",
  "Bahçe Aydınlatma",
  "Bahçe Dekorasyonu",
  "Süs Havuzu",
  "Şelale Yapımı",
  "Kamelya",
  "Pergola",
  "Veranda",
  "Çardak",
  "Çocuk Oyun Alanı",
  "Hazır Rulo Çim",
  "Bitki Bakımı",
  "Çiçek Dikimi",
  "Toprak Serimi",
  "Gübreleme",
  "İlaçlama",
  "Haşere İlaçlama",
  "Böcek İlaçlama",
  "Karınca İlaçlama",
  "Hamam Böceği İlaçlama",
  "Fare İlaçlama",
  "Yılan Yakalama",
  "Arı Kovanı Taşıma",
  "Havuz Yapımı",
  "Havuz Bakımı",
  "Havuz Temizliği",
  "Havuz Kimyasalları",
  "Havuz Seramiği",
  "Havuz Pompası",
  "Havuz Filtresi",
  "Havuz Motoru",
  "Jakuzi",
  "Sauna",
  "Buhar Odası",
  "Sera Kurulumu",
  "Sera Tamiri",
  "Sera Bakımı",
  "Tarla Sulama",
  "Damla Sulama",
  "Yağmurlama Sulama",
  "Kuyu Açma",
  "Sondaj",
  "Artezyen",
  "Su Kuyusu",
  "Traktör Hizmeti",
  "Biçerdöver",
  "Tarım Makinesi",
  "Çiftlik Hizmetleri",
  "Ahır Yapımı",
  "Hayvan Barınağı",
  "Ev Temizliği",
  "Ofis Temizliği",
  "İnşaat Sonrası Temizlik",
  "Dış Cephe Cam Temizliği",
  "Cam Temizliği",
  "Koltuk Yıkama",
  "Halı Yıkama",
  "Yatak Yıkama",
  "Stor Perde Yıkama",
  "Yerinde Halı Yıkama",
  "Buharlı Temizlik",
  "Dezenfeksiyon",
  "Apartman Temizliği",
  "Merdiven Temizliği",
  "Fabrika Temizliği",
  "Okul Temizliği",
  "Hastane Temizliği",
  "AVM Temizliği",
  "Otel Temizliği",
  "Kafe Temizliği",
  "Restoran Temizliği",
  "Çöp Ev Temizliği",
  "Boş Ev Temizliği",
  "Evden Eve Nakliyat",
  "Şehirlerarası Nakliyat",
  "Ofis Taşıma",
  "Parça Eşya Taşıma",
  "Piyano Taşıma",
  "Kasa Taşıma",
  "Ambalajlama",
  "Eşya Paketleme",
  "Mobilya Sökme",
  "Mobilya Kurulumu",
  "Asansörlü Nakliyat",
  "Depolama",
  "Eşya Depolama",
  "Yük Taşıma",
  "Kurye",
  "Moto Kurye",
  "Panelvan Taşıma",
  "Kamyonet Nakliye",
  "Kamyon Nakliye",
  "Oto Tamir",
  "Oto Servis",
  "Oto Elektrik",
  "Oto Elektronik",
  "Oto Kaporta",
  "Oto Boya",
  "Oto Pasta Cila",
  "Oto Seramik Kaplama",
  "Oto Boyasız Göçük",
  "Oto Cam",
  "Oto Cam Filmi",
  "Oto Ekspertiz",
  "Oto Mekanik",
  "Oto Motor",
  "Oto Şanzıman",
  "Oto Fren",
  "Oto Debriyaj",
  "Oto Süspansiyon",
  "Oto Rot Balans",
  "Oto Lastik",
  "Lastikçi",
  "Jant Tamiri",
  "Jant Boyama",
  "Jant Düzeltme",
  "Akü Değişimi",
  "Oto Klima",
  "Oto Klima Gaz Dolumu",
  "Oto Klima Tamiri",
  "Oto Döşeme",
  "Oto Koltuk Döşeme",
  "Oto Tavan Döşeme",
  "Oto Müzik Sistemi",
  "Oto Teyp",
  "Oto Alarm",
  "Oto Kamera",
  "Oto Multimedya",
  "Park Sensörü",
  "Geri Görüş Kamerası",
  "Far Temizleme",
  "Far Parlatma",
  "Far Ayarı",
  "Egzoz",
  "Egzoz Tamiri",
  "Turbo Tamiri",
  "DPF Temizliği",
  "Enjektör Temizliği",
  "Chip Tuning",
  "Yol Yardım",
  "Oto Kurtarıcı",
  "Çekici",
  "Motosiklet Tamiri",
  "Motosiklet Servisi",
  "Motosiklet Elektrik",
  "Motosiklet Lastik",
  "Bisiklet Tamiri",
  "Elektrikli Bisiklet",
  "ATV Tamiri",
  "Traktör Tamiri",
  "İş Makinesi Tamiri",
  "Kepçe Tamiri",
  "Forklift Servisi",
  "Vinç Servisi",
  "Hidrolik Sistem",
  "Pnömatik Sistem",
  "CNC Operatörü",
  "CNC Torna",
  "CNC Freze",
  "Torna Ustası",
  "Frezeci",
  "Tesviyeci",
  "Metal İşleme",
  "Metal Kesim",
  "Lazer Kesim",
  "Plazma Kesim",
  "Su Jeti Kesim",
  "Büküm",
  "Abkant",
  "Pres",
  "Kalıphane",
  "Makine Bakımı",
  "Makine Revizyon",
  "Rulman Değişimi",
  "Konveyör Sistemleri",
  "Bant Sistemleri",
  "Kompresör Servisi",
  "Hava Kompresörü",
  "Vakum Sistemleri",
  "Endüstriyel Fan",
  "Reklam Tabelası",
  "LED Tabela",
  "Işıklı Tabela",
  "Işıksız Tabela",
  "Totem Tabela",
  "Pleksi Tabela",
  "Vinil Baskı",
  "Dijital Baskı",
  "Folyo Kaplama",
  "Araç Giydirme",
  "Cam Giydirme",
  "Cephe Giydirme",
  "Matbaa",
  "Kartvizit Baskı",
  "Broşür Baskı",
  "Afiş Baskı",
  "Branda Baskı",
  "UV Baskı",
  "Lazer Kazıma",
  "Kupa Baskı",
  "Tişört Baskı",
  "Fotoğrafçı",
  "Düğün Fotoğrafçısı",
  "Drone Çekimi",
  "Video Çekimi",
  "Tanıtım Filmi",
  "Organizasyon",
  "Düğün Organizasyonu",
  "Nişan Organizasyonu",
  "Sünnet Organizasyonu",
  "Doğum Günü Organizasyonu",
  "Ses Sistemi",
  "Işık Sistemi",
  "Sahne Kurulumu",
  "DJ",
  "Sunucu",
  "Animasyon",
  "Palyaço",
  "Berber",
  "Kuaför",
  "Kadın Kuaförü",
  "Erkek Kuaförü",
  "Gelin Başı",
  "Makyaj",
  "Profesyonel Makyaj",
  "Cilt Bakımı",
  "Lazer Epilasyon",
  "Kalıcı Makyaj",
  "Protez Tırnak",
  "Manikür",
  "Pedikür",
  "Masaj",
  "Spa",
  "Güzellik Merkezi",
  "Veteriner",
  "Evcil Hayvan Bakımı",
  "Köpek Eğitimi",
  "Kedi Bakımı",
  "Pet Kuaförü",
  "Pet Oteli",
  "Pet Taşıma",
  "Yazılım Geliştirici",
  "Mobil Uygulama Geliştirici",
  "Flutter Geliştirici",
  "Android Geliştirici",
  "iOS Geliştirici",
  "Web Tasarım",
  "Web Yazılım",
  "E-Ticaret Sitesi",
  "WordPress",
  "SEO Uzmanı",
  "Google Ads",
  "Sosyal Medya Uzmanı",
  "Grafik Tasarım",
  "Logo Tasarımı",
  "UI Tasarım",
  "UX Tasarım",
  "3D Tasarım",
  "Animasyon",
  "Video Kurgu",
  "Video Editör",
  "İçerik Üretici",
  "Metin Yazarı",
  "Çevirmen",
  "İngilizce Çeviri",
  "Almanca Çeviri",
  "Rusça Çeviri",
  "Arapça Çeviri",
  "Muhasebeci",
  "Mali Müşavir",
  "Vergi Danışmanı",
  "Hukuk Danışmanı",
  "Avukat",
  "İcra Takibi",
  "Sigorta Danışmanı",
  "Emlak Danışmanı",
  "Ekspertiz",
  "Gayrimenkul Değerleme",
  "Mimar",
  "İç Mimar",
  "İnşaat Mühendisi",
  "Makine Mühendisi",
  "Elektrik Mühendisi",
  "Harita Mühendisi",
  "Jeoloji Mühendisi",
  "Zemin Etüdü",
  "Harita Ölçümü",
  "Drone Haritalama",
  "İSG Uzmanı",
  "Şantiye Şefi",
  "Kontrol Mühendisi",
  "Danışman",
  "Proje Yönetimi",
  "Kalite Kontrol",
  "Laboratuvar",
  "Su Analizi",
  "Toprak Analizi",
  "Beton Testi",
  "Kaynak Kontrol",
  "NDT Testi",
  "Ultrasonik Test",
  "Radyografik Test",
  "Manyetik Test",
  "Penetrant Test",
  "Asansör Bakımı",
  "Asansör Montajı",
  "Asansör Revizyonu",
  "Yük Asansörü",
  "Yürüyen Merdiven",
  "Yürüyen Bant",
  "Vinç Operatörü",
  "Kule Vinç Operatörü",
  "Forklift Operatörü",
  "Greyder Operatörü",
  "Dozer Operatörü",
  "Ekskavatör Operatörü",
  "Loder Operatörü",
  "Silindir Operatörü",
  "Mini Kepçe Operatörü",
  "Kaynak Operatörü",
  "Makine Operatörü",
  "Paketleme",
  "Depo Hizmeti",
  "Depo Yönetimi",
  "Stok Yönetimi",
  "Lojistik",
  "Kargo Hizmeti",
  "Hızlı Kurye",
  "VIP Transfer",
  "Şoför",
  "Özel Şoför",
  "Vale",
  "Oto Yıkama",
  "Detaylı Araç Temizliği",
  "Motor Yıkama",
  "Tekne Temizliği",
  "Yat Bakımı",
  "Tekne Boyama",
  "Tekne Tamiri",
  "Marin Elektrik",
  "Marin Motor",
  "Deniz Motoru",
  "Yelken Tamiri",
  "Branda Dikimi",
  "Dikiş",
  "Terzi",
  "Kuru Temizleme",
  "Ayakkabı Tamiri",
  "Çanta Tamiri",
  "Saat Tamiri",
  "Kuyumcu",
  "Mücevher Tamiri",
  "Altın Tamiri",
  "Gümüş Tamiri",
  "Saat Pili Değişimi",
  "Müzik Öğretmeni",
  "Piyano Dersi",
  "Gitar Dersi",
  "Keman Dersi",
  "Davul Dersi",
  "Yüzme Eğitmeni",
  "Fitness Antrenörü",
  "Pilates Eğitmeni",
  "Yoga Eğitmeni",
  "Özel Ders",
  "Matematik Özel Ders",
  "İngilizce Özel Ders",
  "KPSS Eğitmeni",
  "YKS Eğitmeni",
  "LGS Eğitmeni",
  "Koçluk",
  "Yaşam Koçu",
  "Diyetisyen",
  "Psikolog",
  "Psikolojik Danışman",
  "Fizyoterapist",
  "Hemşire",
  "Hasta Bakıcı",
  "Yaşlı Bakımı",
  "Çocuk Bakıcısı",
  "Bebek Bakıcısı",
  "Refakatçi",
  "Evde Sağlık",
  "Evde Serum",
  "Evde Fizik Tedavi",
  "Evde Kan Alma",
  "Engelli Bakımı",
  "Cenaze Hizmetleri",
  "Mezar Yapımı",
  "Mezar Bakımı",
  "Mezar Temizliği",
  "Kar Küreme",
  "Tuzlama",
  "Afet Temizliği",
  "Sel Temizliği",
  "Yangın Sonrası Temizlik",
  "Duman Temizliği",
];

String selectedCity = "Antalya";
@override
void initState() {
  super.initState();
  userService.getCraftsmen().listen((users) {
    setState(() {
      allCraftsmen = users.where((u) => !u.isFrozen).toList();

      filteredCraftsmen = allCraftsmen;

      loading = false;
    });
  });
}

void filterCraftsmen() {
  final query = searchController.text.trim().toLowerCase();

  filteredCraftsmen = allCraftsmen.where((user) {
    final fullName =
    "${user.firstName} ${user.lastName}".toLowerCase();

    final profession =
    user.professions.join(", ").toLowerCase();

    final city =
    user.city.toLowerCase();

    final searchOk =
        query.isEmpty ||
            fullName.contains(query) ||
            profession.contains(query);

    final cityOk =
        selectedCity.isEmpty ||
            city == selectedCity.toLowerCase();

    return searchOk && cityOk;
  }).toList();

  filteredCraftsmen.sort((a, b) {
    final rating =
    b.rating.compareTo(a.rating);

    if (rating != 0) return rating;

    return b.completedJobs.compareTo(
      a.completedJobs,
    );
  });

  setState(() {});
}
@override
Widget build(BuildContext context) {
  final l10n = AppLocalizations.of(context)!;
return Scaffold(
backgroundColor: const Color(0xffF5F7FA),
appBar: AppBar(
centerTitle: true,
elevation: 0,
backgroundColor: Colors.white,
  title: Text(
    l10n.searchCraftsmanTitle,
    style: const TextStyle(
      color: Colors.black,
      fontWeight: FontWeight.bold,
    ),
  ),
),
body: SingleChildScrollView(
padding: const EdgeInsets.all(18),
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
  Text(
    l10n.searchServiceTitle,
    style: const TextStyle(
      fontSize: 22,
      fontWeight: FontWeight.bold,
    ),
  ),

const SizedBox(height: 20),

  Autocomplete<String>(
    optionsBuilder: (TextEditingValue value) {
      if (value.text.trim().isEmpty) {
        return const Iterable<String>.empty();
      }

      String search = value.text
          .toLowerCase()
          .replaceAll("ç", "c")
          .replaceAll("ğ", "g")
          .replaceAll("ı", "i")
          .replaceAll("ö", "o")
          .replaceAll("ş", "s")
          .replaceAll("ü", "u");

      final startsWith = jobs.where((job) {
        final j = job
            .toLowerCase()
            .replaceAll("ç", "c")
            .replaceAll("ğ", "g")
            .replaceAll("ı", "i")
            .replaceAll("ö", "o")
            .replaceAll("ş", "s")
            .replaceAll("ü", "u");

        return j.startsWith(search);
      });

      final contains = jobs.where((job) {
        final j = job
            .toLowerCase()
            .replaceAll("ç", "c")
            .replaceAll("ğ", "g")
            .replaceAll("ı", "i")
            .replaceAll("ö", "o")
            .replaceAll("ş", "s")
            .replaceAll("ü", "u");

        return !j.startsWith(search) &&
            j.contains(search);
      });

      return [
        ...startsWith,
        ...contains,
      ];
    },

    onSelected: (value) {
      searchController.text = value;
      filterCraftsmen();
    },

    fieldViewBuilder: (
        context,
        controller,
        focusNode,
        onEditingComplete,
        ) {
      controller.text = searchController.text;

      return TextField(
        controller: controller,
        focusNode: focusNode,
        onChanged: (value) {
          searchController.text = value;
          filterCraftsmen();
        },
        decoration: InputDecoration(
          hintText: l10n.craftsmanSearchHint,
          prefixIcon: const Icon(Icons.search),
          suffixIcon: IconButton(
            icon: const Icon(Icons.clear),
            onPressed: () {
              controller.clear();
              searchController.clear();
              filterCraftsmen();
            },
          ),
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
          ),
        ),
      );
    },
  ),

  SizedBox(height: 20),

DropdownButtonFormField<String>(
value: selectedCity,
decoration: InputDecoration(
filled: true,
fillColor: Colors.white,
prefixIcon: const Icon(Icons.location_on),
border: OutlineInputBorder(
borderRadius: BorderRadius.circular(16),
),
),
items: cities
.map(
(e) => DropdownMenuItem(
value: e,
child: Text(e),
),
)
.toList(),
onChanged: (v) {
  setState(() {
    selectedCity = v!;
  });

  filterCraftsmen();
},
),

const SizedBox(height: 30),

  SizedBox(
    width: double.infinity,
    height: 58,
    child: ElevatedButton(
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.green,
        foregroundColor: Colors.white,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
        ),
      ),
      onPressed: () {
        filterCraftsmen();
      },
      child: Text(
        l10n.searchCraftsmanButton,
        style: TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
      ),
    ),
  ),

const SizedBox(height: 35),

 Text(
  l10n.popularCategories,
style: TextStyle(
fontSize: 22,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 15),

Wrap(
spacing: 10,
runSpacing: 10,
children: jobs.take(12).map((job) {
  return InkWell(
    borderRadius: BorderRadius.circular(14),
    onTap: () {
      searchController.text = job;
      filterCraftsmen();
      setState(() {});
    },
    child: Container(
      padding: const EdgeInsets.symmetric(
        horizontal: 16,
        vertical: 10,
      ),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: Colors.grey.shade300,
        ),
      ),
      child: Text(
        job,
        style: TextStyle(
          fontWeight: FontWeight.w600,
        ),
      ),
    ),
  );
}).toList(),
),

const SizedBox(height: 35),

Text(
  l10n.featuredCraftsmen,
style: TextStyle(
fontSize: 22,
fontWeight: FontWeight.bold,
),
),
  const SizedBox(height: 8),

  Text(
    l10n.topRatedCraftsmenFirst,
    style: TextStyle(
      color: Colors.grey,
      fontSize: 14,
    ),
  ),
const SizedBox(height: 15),

  if (loading)
    const Center(
      child: Padding(
        padding: EdgeInsets.all(30),
        child: CircularProgressIndicator(),
      ),
    )
  else if (filteredCraftsmen.isEmpty)
  Padding(
  padding: const EdgeInsets.all(30),
  child: Center(
  child: Text(
  l10n.noCraftsmenFound,
  style: const TextStyle(
  fontSize: 18,
  fontWeight: FontWeight.bold,
  ),
  ),
  ),
  ),
    ListView.builder(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      itemCount: filteredCraftsmen.length,
      itemBuilder: (context, index) {

        final user = filteredCraftsmen[index];

        return Container(
          margin: const EdgeInsets.only(bottom: 18),

          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(22),
            boxShadow: [
              BoxShadow(
                color: Colors.black12,
                blurRadius: 12,
                offset: const Offset(0,5),
              )
            ],
          ),

          child: Padding(
            padding: const EdgeInsets.all(16),

            child: Column(
              children: [

                Row(
                  children: [

                    CircleAvatar(
                      radius: 38,

                      backgroundImage:
                      user.profilePhoto.isNotEmpty
                          ? NetworkImage(user.profilePhoto)
                          : null,

                      child: user.profilePhoto.isEmpty
                          ? const Icon(Icons.person,size:40)
                          : null,
                    ),

                    const SizedBox(width:15),

                    Expanded(
                      child: Column(
                        crossAxisAlignment:
                        CrossAxisAlignment.start,

                        children: [

                          Text(
                            "${user.firstName} ${user.lastName}",

                            style: const TextStyle(
                              fontSize:18,
                              fontWeight: FontWeight.bold,
                            ),
                          ),

                          const SizedBox(height:5),

                          Text(
                            user.professions.join(", "),
                            style: TextStyle(
                              color: Colors.grey.shade700,
                            ),
                          ),

                          const SizedBox(height:8),

                          Row(
                            children: [

                              const Icon(
                                Icons.star,
                                color: Colors.amber,
                                size:20,
                              ),

                              const SizedBox(width:4),

                              Text(
                                user.rating.toStringAsFixed(1),
                                style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                ),
                              ),

                              const SizedBox(width:10),
                              Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 10,
                                  vertical: 5,
                                ),
                                decoration: BoxDecoration(
                                  color: index == 0
                                      ? Colors.amber
                                      : index == 1
                                      ? Colors.grey
                                      : index == 2
                                      ? Colors.brown
                                      : Colors.blue,
                                  borderRadius: BorderRadius.circular(20),
                                ),
                                child: Text(
                                  index == 0
                                      ? "🥇 1"
                                      : index == 1
                                      ? "🥈 2"
                                      : index == 2
                                      ? "🥉 3"
                                      : "#${index + 1}",
                                  style: const TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),

                              const SizedBox(width: 8),
                              GestureDetector(
                                onTap: () {
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                      builder: (_) => CommentsPage(
                                        userId: user.uid,
                                        userName:
                                        "${user.firstName} ${user.lastName}",
                                      ),
                                    ),
                                  );
                                },
                                child: Container(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 10,
                                    vertical: 5,
                                  ),
                                  decoration: BoxDecoration(
                                    color: Colors.amber.shade50,
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Text(
                                    l10n.comments,
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                              ),

                            ],
                          ),

                          const SizedBox(height:8),

                          Row(
                            children: [

                              const Icon(
                                Icons.location_on,
                                color: Colors.red,
                                size:18,
                              ),

                              const SizedBox(width:5),

                              Text(
                                "${user.city} / ${user.district}",
                              ),

                            ],
                          ),

                          const SizedBox(height:8),

                          Text(
                            "${user.completedJobs} ${l10n.completedJobs}",
                          ),
                          const SizedBox(height: 12),

                      Row(
                        children: [
                      Expanded(
                      child: ElevatedButton.icon(
                      style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.red,
                        foregroundColor: Colors.white,
                        minimumSize: const Size(double.infinity, 48),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      onPressed: () async {
                        await favoriteService.toggleFavorite(user.uid);

                        final isFav =
                        await favoriteService.isFavorite(user.uid);

                        setState(() {
                          if (isFav) {
                            favoriteUsers.add(user.uid);
                          } else {
                            favoriteUsers.remove(user.uid);
                          }
                        });

                        if (!mounted) return;

                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            content: Text(
                              isFav
                                  ? l10n.addedToFavorites
                                  : l10n.removedFromFavorites,
                            ),
                          ),
                        );
                      },
                      icon: Icon(
                        favoriteUsers.contains(user.uid)
                            ? Icons.favorite
                            : Icons.favorite_border,
                      ),
                      label: Text(
                        favoriteUsers.contains(user.uid)
                            ? l10n.inFavorites
                            : l10n.addToFavorites,
                      ),
                    ),
          ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ],
                ),

              ],
            ),
          ),
        );

      },
    ),
],
),
),
);
}
}